spring:
  application.name: default-name
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
